export const MALTA_SERVICE_LOCATIONS = [
  { key: 'sliema', label: 'Sliema' },
  { key: 'st-julians', label: "St Julian's" },
  { key: 'valletta', label: 'Valletta' },
  { key: 'gzira', label: 'Gzira' },
  { key: 'msida', label: 'Msida' },
  { key: 'birkirkara', label: 'Birkirkara' },
  { key: 'mosta', label: 'Mosta' },
  { key: 'naxxar', label: 'Naxxar' },
  { key: 'qormi', label: 'Qormi' },
  { key: 'rabat', label: 'Rabat' },
  { key: 'mellieha', label: 'Mellieha' },
  { key: 'bugibba', label: 'Bugibba' },
  { key: 'st-pauls-bay', label: "St Paul's Bay" },
  { key: 'marsaskala', label: 'Marsaskala' },
  { key: 'marsaxlokk', label: 'Marsaxlokk' },
  { key: 'zabbar', label: 'Zabbar' },
  { key: 'fgura', label: 'Fgura' },
  { key: 'paola', label: 'Paola' },
  { key: 'marsa', label: 'Marsa' },
  { key: 'luqa', label: 'Luqa' },
  { key: 'zejtun', label: 'Zejtun' },
] as const;

