declare const process: {
  env: {
    EXPO_PUBLIC_API_URL?: string;
    EXPO_PUBLIC_API_LOGGING?: string;
    EXPO_PUBLIC_ALLOW_MOCK_PURCHASES?: string;
    EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
    EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID?: string;
    EXPO_PUBLIC_REVENUECAT_API_KEY_IOS?: string;
    EAS_BUILD_PROFILE?: string;
  };
};
